[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "http://www.kleros.io/*" 
  to = "https://kleros.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.kleros.io/*" 
  to = "https://kleros.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/contacto"
  to = "/es/contact"
  status = 301
  force = true

[[redirects]]
  from = "/contact"
  to = "/en/contact"
  status = 301
  force = true

[[redirects]]
  from = "/fr/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/ko/*"
  to = "/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/es/*"
  to = "/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/ru/*"
  to = "/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/tr/*"
  to = "/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/pt/*"
  to = "/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/zh/*"
  to = "/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/pt-br/*"
  to = "/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/slack"
  to = "https://join.slack.com/t/kleros/shared_invite/zt-33tbhvg02-CTtTLxFm9wiHMyAjhyClBA"
  status = 301
  force = false

[[redirects]]
  from = "/industries"
  to = "https://kleros.notion.site/Industry-Guides-acf664cf199242e1be7871ddd17f2b6d"
  status = 301
  force = false
